# The Docker image that will be used to build your app
image: ruby:2.7
# Functions that should be executed before the build script is run
before_script:
  - cd site
  - gem update --system
  - bundle install

pages:
  script:   
    - bundle exec jekyll build --destination public
    - bundle exec just-the-docs rake search:init
    - cd ..
    - mv site/public public

  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
