title: NDE documentation

#favicon_ico: "/assets/images/evidenticone.png"

company_name: Evident Industrial

email: nde_support@evidentscientific.com

baseurl: "/NDE_Open_File_Format"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

repository: Evident-Industrial/NDE_Open_File_Format
remote_theme: just-the-docs/just-the-docs@v0.5.4

# Aux links for the upper right navigation
aux_links:
  "NDE_Open_File_Format on Github":
    - "//github.com/Evident-Industrial/NDE_Open_File_Format" 

aux_links_new_tab: true

nav_external_links:
  - title: NDE_Open_File_Format on Github
    url: https://github.com/Evident-Industrial/NDE_Open_File_Format

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
  
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 6
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false